export async function fetchAthletePerformance(athleteId, year) {
  // TODO: Make this work
  return {
    "entrant": {
      "competitorId": "1005789",
      "competitorName": "Josh Larson",
      "firstName": "Josh",
      "lastName": "Larson",
      "status": "ACT",
      "postCompStatus": "",
      "gender": "M",
      "profilePicS3key": "pukie.png",
      "countryShortCode": "",
      "regionalCode": "3",
      "regionId": "10",
      "regionName": "North Central",
      "divisionId": "1",
      "profession": "0",
      "affiliateId": "6690",
      "affiliateName": "CrossFit Waukee",
      "age": "28",
      "height": "",
      "weight": "",
      "teamCaptain": "0"
    },
    "ui": {
      "highlight": true
    },
    "scores": [
      {
        "ordinal": 1,
        "rank": "136007",
        "score": "12250000",
        "scoreDisplay": "225 reps",
        "mobileScoreDisplay": "",
        "scoreIdentifier": "e4757604e007af7dfe9d",
        "scaled": "0",
        "video": "0",
        "breakdown": "7 rounds +\n1 toes-to-bars",
        "judge": "Rian Moe",
        "affiliate": "CrossFit Waukee",
        "heat": "",
        "lane": ""
      },
      {
        "ordinal": 2,
        "rank": "117138",
        "score": "11100114",
        "scoreDisplay": "10:06",
        "mobileScoreDisplay": "",
        "scoreIdentifier": "7874175d4760b4ac935a",
        "scaled": "0",
        "video": "0",
        "time": 606,
        "breakdown": "110 reps\n205 lb.",
        "judge": "Tyler Lloyd",
        "affiliate": "CrossFit Des Moines",
        "heat": "",
        "lane": ""
      },
      {
        "ordinal": 3,
        "rank": "89380",
        "score": "12050114",
        "scoreDisplay": "205 lb",
        "mobileScoreDisplay": "",
        "scoreIdentifier": "e76d280b7b10adfc2a7e",
        "scaled": "0",
        "video": "0",
        "breakdown": "205 lb.",
        "time": 606,
        "judge": "Tyler Lloyd",
        "affiliate": "CrossFit Des Moines",
        "heat": "",
        "lane": ""
      },
      {
        "ordinal": 4,
        "rank": "143694",
        "score": "9280011",
        "scoreDisplay": "13:49 - s",
        "mobileScoreDisplay": "",
        "scoreIdentifier": "a7c9de025b8c459c68c7",
        "scaled": "1",
        "video": "0",
        "time": 829,
        "breakdown": "928 reps",
        "judge": "Rian Moe",
        "affiliate": "CrossFit Waukee",
        "heat": "",
        "lane": ""
      },
      {
        "ordinal": 5,
        "rank": "117330",
        "score": "10300490",
        "scoreDisplay": "30 reps",
        "mobileScoreDisplay": "",
        "scoreIdentifier": "a17f3d02adf9647ee3e4",
        "scaled": "0",
        "video": "0",
        "time": 50,
        "breakdown": "21 deadlifts\n9 handstand push-ups",
        "judge": "Reggie Hoegh",
        "affiliate": "CrossFit Waukee",
        "heat": "",
        "lane": ""
      },
      {
        "ordinal": 6,
        "rank": "150320",
        "score": "1290000",
        "scoreDisplay": "129 reps - s",
        "mobileScoreDisplay": "",
        "scoreIdentifier": "069cf62393e66be2e327",
        "scaled": "1",
        "video": "0",
        "breakdown": "3 thr. 3 PU \n6 thr. 6 PU \n9 thr. 9 PU \n12 thr. 12 PU \n15 thr. 15 PU \n18 thr. 18 PU \n3 thr.",
        "judge": "Rian Moe",
        "affiliate": "CrossFit Waukee",
        "heat": "",
        "lane": ""
      }
    ],
    "overallRank": "128622",
    "overallScore": "753869",
    "nextStage": ""
  }
}
